### PR TITLE
Allow optimisation for non-MSVC compilers

### PR DESCRIPTION
**Pull request by mkae**
This speeds up the critical functions by about a factor of **10**! :-)

(Inadvertendly there is my change of the `README.md` in here... _Please skip over that!_)

### CODE REVIEW

**Comment by KimuraRyo** [comment]
Thank you for your contribution. `libbsdf` does not depend on Qt and OSG, so they should not be described in `README.md`.

**Comment by mkae** [comment]
Yes, of course, that was a copy&paste from BSDFProcessor. Will fix that some time.

**Comment by mkae** [comment]
Done in https://github.com/mkae/libbsdf/commit/54e3c051268c02b2b1992e73bcbc159d6f2c6089

**Comment by mkae** [comment]
BTW, @KimuraRyo, is it a problem if I enable SSE3 instead of SSE2?

**Comment by KimuraRyo** [comment]
I don't know. Current settings don't cause any problem on MSVC and Xcode. If you want to change them in CMakeLists.txt, please do it only for MSYS2 using `if` clause.

**Comment by mkae** [comment]
OK, will change it accordingly.

**Pull request closed without merging**
